dolweb/blog/urls.py
# Copyright (c) 2018 Dolphin Emulator Website Contributors
# SPDX-License-Identifier: MIT

from django.conf import settings
from django.conf.urls import url, include
from dolweb.blog.feeds import SeriesFeed
from dolweb.blog.views import series_index, etherpad_event

urlpatterns = [
    url(r'^', include('zinnia.urls', namespace='zinnia')),
    url(r'^feeds/series/(?P<pk>[0-9]+)$', SeriesFeed(), name='dolweb_blog_series_feed'),
    url(r'^series#series-(?P<uid>[0-9]+)$', series_index, name='dolweb_blog_series'),
    url(r'^series$', series_index, name='dolweb_blog_series_index'),
]

if settings.BLOG_ETHERPAD_URL:
    urlpatterns += [
        url(r'^etherpad/event$', etherpad_event),
    ]

dolweb/urls.py
# Copyright (c) 2018 Dolphin Emulator Website Contributors
# SPDX-License-Identifier: MIT

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.base import RedirectView
from dolweb.homepage.views import home
from dolweb.management.views import run_command

# Monkey patching ftw...
import dolweb.utils.monkey

admin.autodiscover()

urlpatterns = [
    # Homepage
    url(r'^$', home, name='home'),

    # Media (image gallery, link to videos)
    url(r'^media/', include('dolweb.media.urls')),

    # Documentation (FAQ and guides)
    url(r'^docs/', include('dolweb.docs.urls')),

    # Downloads
    url(r'^download/', include('dolweb.downloads.urls')),

    # Blog
    url(r'^blog/', include('dolweb.blog.urls')),

    # Compatibility list
    url(r'^compat/', include('dolweb.compat.urls')),

    # Django administration
    url(r'^admin/', admin.site.urls),

    # Management interface
    url(r'^mgmt/(?P<cmd>.+)$', run_command, name='mgmt_run_command'),

    # Auto-update checking.
    url(r'^update/', include('dolweb.update.urls')),

    # ads.txt
    url(r"^ads.txt$", RedirectView.as_view(url=staticfiles_storage.url("ads.txt"))),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

dolweb/blog/models.py
# Copyright (c) 2018 Dolphin Emulator Website Contributors
# SPDX-License-Identifier: MIT

from django.conf import settings
from django.db import models
from django.utils.html import linebreaks
from django.utils.translation import ugettext as _

from zinnia.markups import textile
from zinnia.markups import markdown
from zinnia.markups import restructuredtext
from zinnia.settings import UPLOAD_TO, MARKUP_LANGUAGE
from zinnia.managers import PUBLISHED
from zinnia.models_bases.entry import AbstractEntry


def render_to_html(content):
    if MARKUP_LANGUAGE == 'markdown':
        # TODO: Remove when Zinnia supports non-string Markdown exts.
        import markdown
        from zinnia.settings import MARKDOWN_EXTENSIONS
        from django.utils.encoding import force_text
        return markdown.markdown(force_text(content),
                                 extensions=MARKDOWN_EXTENSIONS,
                                 safe_mode=False)
    elif MARKUP_LANGUAGE == 'textile':
        return textile(content)
    elif MARKUP_LANGUAGE == 'restructuredtext':
        return restructuredtext(content)
    return linebreaks(content)


class BlogSeries(models.Model):
    """Represents a date-ordered sequence of blog entries."""

    name = models.CharField(max_length=255, db_index=True)
    visible = models.BooleanField(default=True)
    image = models.ImageField(
        _('image'), blank=True, upload_to=UPLOAD_TO,
        help_text=_('Used for illustration.'))

    @property
    def entries_reversed(self):
        return self.entries.order_by('publication_date')

    def nth_entry(self, nth, allow_hidden=False):
        """Returns the 1-indexed nth article in series."""
        if nth < 1:
            return None

        qs = self.entries.all()
        if not allow_hidden:
            qs = qs.filter(status=PUBLISHED)

        try:
            return qs.order_by('publication_date')[nth - 1]
        except IndexError:
            return None

    def __str__(self):
        return self.name

    def __repr__(self):
        return '<BlogSeries "%s" (%d entries)>' % (self.name, self.entries.count())


class ForumThreadForEntry(models.Model):
    entry = models.OneToOneField('zinnia.Entry', on_delete=models.CASCADE, related_name='forum_thread')
    thread_id = models.IntegerField()

    def get_absolute_url(self):
        return settings.FORUM_URL_FOR_THREAD.format(id=self.thread_id)

    def __str__(self):
        return "%s -> %s" % (self.entry, self.get_absolute_url())

    def __repr__(self):
        return "<ForumThreadForEntry %s -> thread %d>" % (
            self.entry, self.thread_id
        )

class BlogEntry(AbstractEntry):
    """
    Represents a blog entry. Adds an optional `series` field to the default
    Zinnia model.
    """
    within_series = models.ForeignKey(BlogSeries, on_delete=models.SET_NULL, null=True, blank=True, related_name='entries')
    etherpad_id = models.CharField(max_length=256, null=True, blank=True)

    @property
    def use_collaborative_editing(self):
        return self.etherpad_id and self.draft

    @property
    def draft(self):
        return self.status != PUBLISHED

    # The default Zinnia implementation of this does stupid content sniffing,
    # assuming that if something contains </p> it is raw HTML. That's not true,
    # since Markdown can contain HTML.
    @property
    def html_content(self):
        """
        Returns the "content" field formatted in HTML.
        """
        return render_to_html(self.content)

    # While Zinnia provides html_preview for HTML rendered excerpts,
    # that property doesn't allow custom article excerpts, so we need to roll
    # our own rendered excerpt property.
    @property
    def html_excerpt(self):
        """
        Returns the "excerpt" field formatted in HTML.
        """
        return render_to_html(self.excerpt)

    @property
    def real_image(self):
        """Priorities the entry image, then the series image, if any."""
        if self.image:
            return self.image

        if self.within_series is not None:
            # May be None!
            return self.within_series.image

    @property
    def series_index(self):
        if self.within_series is None:
            return 1

        return (self.within_series.entries
            .filter(publication_date__lt=self.publication_date)
            .exclude(pk=self.pk)
            .count()) + 1

    def relative_entry_in_series(self, offset):
        if self.within_series is None:
            return None

        return self.within_series.nth_entry(self.series_index + offset)

    @property
    def next_entry_in_series(self):
        return self.relative_entry_in_series(1)

    @property
    def previous_entry_in_series(self):
        return self.relative_entry_in_series(-1)

    class Meta(AbstractEntry.Meta):
        abstract = True

dolweb/compat/models.py
# Copyright (c) 2018 Dolphin Emulator Website Contributors
# SPDX-License-Identifier: MIT

from datetime import datetime
from django.conf import settings
from django.core.cache import cache
from django.db import models

import urllib.parse

class Namespace(object):
    MAIN = 0
    TALK = 1
    USER = 2
    USER_TALK = 3
    PROJECT = 4
    PROJECT_TALK = 5
    FILE = 6
    FILE_TALK = 7
    MEDIAWIKI = 8
    MEDIAWIKI_TALK = 9
    TEMPLATE = 10
    TEMPLATE_TALK = 11
    HELP = 12
    HELP_TALK = 13
    CATEGORY = 14
    CATEGORY_TALK = 15

class Text(models.Model):
    id = models.IntegerField(db_column='old_id', primary_key=True)
    data_raw = models.TextField(db_column='old_text')

    @property
    def data(self):
        return self.data_raw

    def __str__(self):
        return 'Blob %d: %s' % (self.id, self.data[:100])

    class Meta:
        db_table = 'text'
        verbose_name = 'MediaWiki Text Blob'
        verbose_name_plural = 'MediaWiki Text Blobs'

class Revision(models.Model):
    id = models.IntegerField(db_column='rev_id', primary_key=True)
    page = models.ForeignKey('Page', on_delete=models.PROTECT, db_column='rev_page', related_name='+')
    text = models.ForeignKey('Text', on_delete=models.PROTECT, db_column='rev_text_id', related_name='+')
    timestamp = models.CharField(db_column='rev_timestamp', max_length=14)

    def __str__(self):
        return '%s for %s' % (self.timestamp, self.page)

    class Meta:
        db_table = 'old_revision'
        verbose_name = 'MediaWiki Revision'
        verbose_name_plural = 'MediaWiki Revisions'

class Page(models.Model):
    id = models.IntegerField(db_column='page_id', primary_key=True)
    namespace = models.IntegerField(db_column='page_namespace')
    title_url = models.CharField(db_column='page_title', max_length=255)
    len = models.IntegerField(db_column='page_len')
    latest = models.ForeignKey('Revision', on_delete=models.PROTECT, db_column='page_latest', related_name='+')
    is_redirect = models.BooleanField(db_column='page_is_redirect', default=False)

    @property
    def wiki_url(self):
        u = self.title_url
        if u.startswith('Ratings/'):
            u = u[len('Ratings/'):]
        return settings.WIKI_URL + 'index.php?title=%s' % urllib.parse.quote(u)

    @property
    def title(self):
        s = self.title_url.replace('_', ' ')
        if s.startswith('Ratings/'):
            s = s[len('Ratings/'):]
        return s

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'page'
        ordering = ['namespace', 'title_url']
        verbose_name = 'MediaWiki Page'
        verbose_name_plural = 'MediaWiki Pages'

class Category(models.Model):
    id = models.IntegerField(db_column='cat_id', primary_key=True)
    title = models.CharField(db_column='cat_title', max_length=255)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'category'
        ordering = ['title']
        verbose_name = 'MediaWiki Category'
        verbose_name_plural = 'MediaWiki Categories'

class CategoryLink(models.Model):
    id = models.IntegerField(primary_key=True, db_column='cl_sortkey') ## UGLY, not PK in DB
    page = models.ForeignKey('Page', on_delete=models.PROTECT, db_column='cl_from', related_name='+')
    cat = models.CharField(db_column='cl_to', max_length=255)

    def __str__(self):
        return 'Link from %s to %s' % (self.page, self.cat)

    class Meta:
        db_table = 'categorylinks'
        ordering = ['cat', 'page']
        verbose_name = 'MediaWiki Category Link'
        verbose_name_plural = 'MediaWiki Category Links'

def get_rated_games():
    count = cache.get('rating_count')
    if count is None:
        count = Page.objects.filter(namespace=Namespace.TEMPLATE, title_url__startswith='Ratings/',
                                    latest__text__data_raw__in=('1', '2', '3', '4', '5')).count()
        cache.set('rating_count', count, 300)
    return count

def get_rating_count(n):
    if n < 1 or n > 5:
        return 0

    count = cache.get('rating_count_%d' % n)
    if count is None:
        count = Page.objects.filter(namespace=Namespace.TEMPLATE, title_url__startswith='Ratings/',
                                    latest__text__data_raw=str(n)).count()
        cache.set('rating_count_%d' % n, count, 300)

    return count

def get_category_id(name):
    id = cache.get('category_name_%s' % name)
    if id is None:
        try:
            id = Category.objects.get(title=name)
        except Category.DoesNotExist:
            return 0
        cache.set('category_name_%s' % name, id)

    return id

dolweb/blog/views.py
# Copyright (c) 2018 Dolphin Emulator Website Contributors
# SPDX-License-Identifier: MIT

from annoying.decorators import render_to
from django.conf import settings
from django.core.paginator import Paginator, EmptyPage
from django.db import models
from django.dispatch import receiver
from django.http import Http404, HttpResponse
from zinnia.managers import PUBLISHED
from zinnia.models.entry import Entry
from django.views.decorators.csrf import csrf_exempt
from zinnia.views.mixins.entry_preview import EntryPreviewMixin

from dolweb.blog.models import BlogSeries

import hashlib
import hmac
import json
import requests
import uuid


@render_to('series-index.html')
def series_index(request, page=None, uid=None):
    all_series = BlogSeries.objects.filter(visible=True)

    return {'all_series': all_series}

# TODO(delroth): Ugly. Should really authenticate these requests, but we don't
# have a nice SSO story at the moment.
del EntryPreviewMixin.get_object

@csrf_exempt
def etherpad_event(request):
    if request.method != 'POST':
        raise Http404

    if b' ' not in request.body:
        return HttpResponse('Invalid format', status=400)

    request_hmac, content = request.body.split(b' ', 1)
    hm = hmac.new(
        settings.BLOG_ETHERPAD_HMAC_KEY.encode('ascii'), content,
        hashlib.sha256)
    if hm.hexdigest().encode('ascii') != request_hmac:
        return HttpResponse('Invalid signature', status=403)
    events = json.loads(content)

    last_updates = {}
    for evt in events:
        if evt.get('type') != 'pad_update':
            continue
        last_updates[evt.get('id')] = evt.get('text')

    for pad_id, text in last_updates.items():
        try:
            entry = Entry.objects.get(etherpad_id=pad_id)
            if entry.status == PUBLISHED:
                continue  # Do not auto-sync published articles.
            entry.content = text
            entry.save()
        except Entry.DoesNotExist:
            continue

    return HttpResponse('OK')

# TODO(delroth): Move this to a better place. It cannot be in models.py since
# the Zinnia models depend on importing models.py.
@receiver(models.signals.post_save, sender=Entry)
def add_etherpad_id(sender, instance, created, **kwargs):
    if not settings.BLOG_ETHERPAD_URL or not settings.BLOG_ETHERPAD_API_KEY:
        return
    if instance.etherpad_id:
        return
    instance.etherpad_id = uuid.uuid4()
    url = '%s/api/1/createPad' % settings.BLOG_ETHERPAD_URL
    r = requests.post(url, timeout=5, data={
        'apikey': settings.BLOG_ETHERPAD_API_KEY,
        'padID': instance.etherpad_id,
        'text': instance.content,
    })
    instance.save()

dolweb/blog/templates/zinnia/_base_blog.html
{% extends "_base.html" %}

dolweb/blog/templates/zinnia/_entry_detail.html
{% extends "zinnia/_entry_detail_base.html" %}

dolweb/blog/templates/zinnia/_entry_detail_base.html
{% load comments i18n thumbnail %}
<div id="entry-{{ object.pk }}" class="hentry{% if object.featured %} featured{% endif %}">
  {% if object.draft %}
  <div class="draft-warning blink">
    This article is a draft. Avoid widely sharing this link.
  </div>
  {% endif %}
  {% block entry-header %}
  <div class="entry-header">
    {% block entry-title %}
    <h2 class="entry-title">
      <a href="{{ object.get_absolute_url }}" title="{{ object.title }}" rel="bookmark">
        {{ object.title }}
      </a>
    </h2>
    {% endblock %}
    {% block entry-info %}
    <div class="entry-meta-line">
    <p class="entry-info">
      {% with authors=object.authors.all %}
      {% if authors|length %}
      {% trans "Written by" %}
      {% for author in authors %}
      <span class="vcard author">
        <a href="{{ author.get_absolute_url }}" class="fn url{% if not author.get_full_name %} nickname{% endif %}" rel="author"
           title="{% blocktrans %}Show all {{ author }}'s entries{% endblocktrans %}">{{ author }}</a></span>{% if not forloop.last %}, {% endif %}
      {% endfor %}
      {% trans "on" %}
      {% else %}
      {% trans "Written on" %}
      {% endif %}
      {% endwith %}
      <abbr class="published" title="{{ object.publication_date|date:"c" }}">{{ object.publication_date|date:"DATE_FORMAT" }}</abbr>
    </p>
    {% endblock %}
    {% block entry-last-update %}
    <p class="entry-last-update">
      / {% trans "Last update on" %} <abbr class="updated" title="{{ object.last_update|date:"c" }}">{{ object.last_update|date:"DATE_FORMAT" }}</abbr>
    / <a href="{{ object.short_url }}"
       title="{% blocktrans with object=object.title %}Short URL to {{ object }}{% endblocktrans %}"
       rel="shortlink">{% trans "Short link" %}</a>
    {% if object.forum_thread %}/ <i class="icon-comments"></i> <a href="{{ object.forum_thread.get_absolute_url }}" title="{% trans "Visit forum thread for this article" %}">{% trans "Forum thread" %}</a>{% endif %}
    </p>
    </div>
    {% endblock %}
  </div>
  {% endblock %}

  {% block entry-body %}
  <div class="entry-body">
    {% block entry-content %}
    <div class="entry-content">
      {{ object_content }}

    {% block continue-reading %}
    {% if continue_reading %}
    <p class="continue-reading">
      <a href="{{ object.get_absolute_url }}"
         title="{% blocktrans with object=object.title %}Continue reading {{ object }}{% endblocktrans %}"
         rel="bookmark">
        {% trans "Continue reading" %}
      </a>
    </p>
    {% endif %}
    {% endblock %}

    </div>
    {% endblock %}
    {% if object.forum_thread %}
    <p><i class="icon-comments"></i> {% blocktrans with url=object.forum_thread.get_absolute_url %}You can continue the discussion in the <a href="{{url}}" title="Visit forum thread for this article">forum thread</a> of this article.{% endblocktrans %}</p>{% endif %}
  </div>
  {% endblock %}

  {% block entry-footer %}
  <div class="entry-footer row">
    <div class="col-md-6">
    {% block entry-series %}
    {% if object.within_series %}
    <h4>{% trans "Blog series" %}</h4>
    {% url 'dolweb_blog_series' uid=object.within_series.pk as series_url %}
    <p>{% blocktrans with nth=object.series_index url=series_url series=object.within_series %}This article is number {{ nth }} within the blog series
    <a href="{{ url }}"><em>{{ series }}</em></a>.{% endblocktrans %}
    {% with previous=object.previous_entry_in_series next=object.next_entry_in_series %}
    {% if previous or next %}
      {% if previous %}<a href="{{ previous.get_absolute_url }}">{% trans "‹ Previous article in series" %}</a>{% endif %}
      {% if previous and next %}/{% endif %}
      {% if next %}<a href="{{ next.get_absolute_url }}">{% trans "Next article in series ›" %}</a>{% endif %}
    </p>
    {% endif %}
    {% endwith %}
    {% endif %}
    {% endblock %}
    {% block entry-comments %}
    {% endblock %}
    </div>

    {% block entry-tags %}
    <div class="entry-tags col-md-3">
      <h4>{% trans "Tags" %}</h4>
      <ul class="tag-cloud">
      {% for tag in object.tags_list %}
      <li><a href="{% url 'zinnia:tag_detail' tag %}"
         title="{% blocktrans %}Show all entries tagged by {{ tag }}{% endblocktrans %}"
         rel="tag">{{ tag }}</a></li>
      {% empty %}
      <span class="empty">{% trans "No tags" %}</span>
      {% endfor %}
      </ul>
    </div>
    {% endblock %}
    {% block entry-categories %}
    <div class="entry-categories col-md-3">
      <h4>{% trans "Categories" %}</h4>
      {% with categories=object.categories.all %}
      {% for category in categories %}
      <a href="{{ category.get_absolute_url }}"
         title="{% blocktrans %}Show all entries in {{ category }}{% endblocktrans %}"
         rel="tag category">{{ category }}</a>{% if not forloop.last %}, {% endif %}
      {% empty %}
      <span class="empty">{% trans "No categories" %}</span>
      {% endfor %}{% endwith %}
    </div>
    {% endblock %}
  </div>
  {% endblock %}
</div>

dolweb/blog/templates/zinnia/entry_detail.html
{% extends "zinnia/entry_detail_base.html" %}

dolweb/blog/templates/zinnia/entry_list.html
{% extends "zinnia/base.html" %}
{% load i18n zinnia blog_tags %}

{% block meta-description %}{% trans "Latest entries for" %} {% if category %}{% trans "the category" %} {{ category }}{% if category.description %}: {{ category.description|striptags|safe }}{% endif %}{% endif %}{% if tag %}{% trans "the tag" %} {{ tag }}{% endif %}{% if author %}{% trans "the author" %} {{ author }}{% endif %}{% if page_obj %}{% ifnotequal page_obj.number 1 %} {% trans "page" %} {{ page_obj.number }}{% endifnotequal %}{% endif %}{% endblock %}

{% block link %}
  {{ block.super }}
  {% if category %}
    <link rel="alternate" type="application/rss+xml" title="{% trans "RSS Feed" %} {{ category }}" href="{% url 'zinnia:category_feed' category.tree_path %}" />
  {% endif %}
  {% if tag %}
    <link rel="alternate" type="application/rss+xml" title="{% trans "RSS Feed" %} {{ tag }}" href="{% url 'zinnia:tag_feed' tag.name %}" />
  {% endif %}
  {% if author %}
    <link rel="alternate" type="application/rss+xml" title="{% trans "RSS Feed" %} {{ author }}" href="{% url 'zinnia:author_feed' author.username %}" />
  {% endif %}
{% endblock %}

{% block title %}{% trans "Latest entries" %} {% if category %}| {% trans "Category" %} {{ category }}{% endif %}{% if tag %}| {% trans "Tag" %} {{ tag }}{% endif %}{% if author %}| {% trans "Author" %} {{ author }}{% endif %}{% if page_obj %}{% ifnotequal page_obj.number 1 %} | {% trans "Page" %} {{ page_obj.number }}{% endifnotequal %}{% endif %}{% endblock %}

{% block body-class %}entry-list{% if page_obj %} paginated page-{{ page_obj.number }}{% endif %}{% if category %} category category-{{ category.slug }}{% endif %}{% if tag %} tag tag-{{ tag|slugify }}{% endif %}{% if author %} author author-{{ author|slugify }}{% endif %}{% endblock %}

{% block content %}

{% block content-title %}
{% if category %}
<h1>{% blocktrans %}Category archives: {{ category }}{% endblocktrans %}</h1>
{% if category.description %}
<p>{{ category.description|striptags|safe }}</p>
{% endif %}
{% endif %}

{% if tag %}
<h1>{% blocktrans %}Tag archives: {{ tag }}{% endblocktrans %}</h1>
{% endif %}

{% if author %}
<h1>{% blocktrans %}Author archives: {{ author }}{% endblocktrans %}</h1>
{% endif %}
{% endblock %}

{% block content-loop %}
{% for object in object_list %}
  {% include object.content_template with object_content=object.html_content|cuthere_excerpt|safe continue_reading=1 %}
{% empty %}
  <p class="info">
    <a href="{% url 'admin:zinnia_entry_add' %}">{% trans "No entries yet." %}</a>
  </p>
{% endfor %}
{% endblock %}

{% block content-pagination %}
{% if is_paginated %}
  {% zinnia_pagination page_obj %}
{% endif %}
{% endblock %}

{% block content-related %}
{% endblock %}

{% endblock %}

{% block admin_tools %}
  {% if category and perms.zinnia.change_category %}
  <li>
    <a href="{% url 'admin:zinnia_category_change' category.pk %}" title="{% trans "Edit the category" %}">
      {% trans "Edit the category" %}
    </a>
  </li>
  {% endif %}
  {% if tag and perms.tagging.change_tag %}
  <li>
    <a href="{% url 'admin:tagging_tag_change' tag.pk %}" title="{% trans "Edit the tag" %}">
      {% trans "Edit the tag" %}
    </a>
  </li>
  {% endif %}
  {% if author and perms.auth.change_user %}
  <li>
    <a href="{% url 'admin:auth_user_change' author.pk %}" title="{% trans "Edit the author" %}">
      {% trans "Edit the author" %}
    </a>
  </li>
  {% endif %}
{% endblock %}

dolweb/blog/templates/zinnia/entry_search.html
{% extends "zinnia/entry_list.html" %}
{% load i18n zinnia blog_tags %}

{% block title %}{% blocktrans %}Search results for '{{ pattern }}'{% endblocktrans %}{% endblock title %}

{% block meta-description %}{% blocktrans %}Search results for '{{ pattern }}'{% endblocktrans %}{% endblock meta-description %}

{% block link %}
  {{ block.super }}
  {% if not error %}
  <link rel="alternate" type="application/rss+xml" title="{% blocktrans %}RSS feed of search results for '{{ pattern }}'{% endblocktrans %}" href="{% url 'zinnia:entry_search_feed' %}?pattern={{ pattern }}" />
  {% endif %}
{% endblock link %}

{% block body-class %}{{ block.super }} search {% if error %}search-error{% elif object_list %}search-results{% else %}search-no-results{% endif %}{% endblock body-class %}

{% block content-title %}
<h1>{% blocktrans %}Search results for '{{ pattern }}'{% endblocktrans %}</h1>

{% if error %}
<p class="error">{{ error }}</p>
{% else %}
<p class="feed">
  <a href="{% url 'zinnia:entry_search_feed' %}?pattern={{ pattern }}" title="{% blocktrans %}RSS feed of search results for '{{ pattern }}'{% endblocktrans %}">
    {% blocktrans %}RSS feed of search results for '{{ pattern }}'{% endblocktrans %}
  </a>
</p>
{% endif %}

{% if object_list %}
<p class="success">
  {% blocktrans count entry_count=paginator.count %}{{ entry_count }} entry found{% plural %}{{ entry_count }} entries found{% endblocktrans %}
</p>
{% endif %}

{% endblock content-title %}

{% block content-loop %}
{% if not error %}
{% for object in object_list %}
  {% include object.content_template with object_content=object.html_content|cuthere_excerpt|safe continue_reading=1 %}
{% empty %}
<p class="info">{% trans "Nothing found." %}</p>
{% endfor %}
{% endif %}
{% endblock content-loop %}

{% block content-related %}
<div class="search">
  {% include "zinnia/tags/search_form.html" %}
</div>
{% endblock content-related %}

dolweb/blog/templates/zinnia/skeleton.html
{% extends "zinnia/_base_blog.html" %}
{% load i18n staticfiles %}

{% block "metadescr" %}{% trans "Latest news for Dolphin Emulator" %}{% endblock %}

{# Aweful hack to workaround stupid quotes in block name #}
{% block "title" %}{% block title %}{% trans "Articles" %}{% endblock %}{% endblock %}

{% block "body" %}

<div class="row mt-5">
    <div class="col-md-9 order-md-2">

        {% block breadcrumbs %}{% endblock breadcrumbs  %}
        <div class="mb-3 mt-3">
            <a href="{% url 'zinnia:entry_feed' %}" class="rss-tag" title="{% trans "RSS feed of the latest articles" %}"><i class="bi bi-rss" role="button" aria-label="RSS"></i></a>
        </div>
        {% block slider %}{% endblock slider %}

        {% block content %}{% endblock %}

    </div>
    <div class="col-md-3">
        {% include "blog_sidebar.html" %}
    </div>
</div>

{% comment %}
<div id="content" class="hfeed">
  {% block content %}
  <div class="links">
    <h3>{% trans "Useful links" %}</h3>
    <ul>
      <li>
        <a href="{% url 'zinnia:entry_archive_index' %}" title="{% trans "Weblog index" %}">
          {% trans "Weblog index" %}
        </a>
      </li>
      <li>
        <a href="{% url 'zinnia:sitemap' %}" title="{% trans "Sitemap" %}">
          {% trans "Sitemap" %}
        </a>
      </li>
    </ul>
  </div>
  <div class="search">
    <h3>{% trans "Search" %}</h3>
    {% include "zinnia/tags/search_form.html" %}
  </div>
  {% endblock content %}
</div>
<div id="sidebar">
  {% block sidebar %}
  {% endblock sidebar %}
</div>
{% endcomment %}
{% endblock %}